kind: Deployment
apiVersion: apps/v1
metadata:
   name: pathania
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pathania
   template:
      metadata:
        labels:
          app: pathania
      spec:
       containers:
        - name: pathania
          image: anupathania/pipeline-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
