kind: Service                             
apiVersion: v1
metadata:
  name: pathania
  labels:
    app: pathania
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: pathania                    
  type: LoadBalancer    
